sonar.projectKey=ReTiCh-Corp_ReTiCh-API-Gateway
sonar.organization=retich-corp

# Sources and tests
sonar.sources=.
sonar.exclusions=**/*_test.go,**/vendor/**
sonar.tests=.
sonar.test.inclusions=**/*_test.go

# Go coverage report
sonar.go.coverage.reportPaths=coverage

# Coverage exclusions
sonar.coverage.exclusions=cmd/server/main.go

# Encoding of the source code
sonar.sourceEncoding=UTF-8