sonar.projectKey=ReTiCh-Corp_ReTiCh-API-Gateway
sonar.organization=retich-corp

# Sources and tests
sonar.sources=cmd/server
sonar.tests=cmd/server
sonar.test.inclusions=**/*_test.go
sonar.exclusions=**/*_test.go,vendor/**

# Go coverage report
sonar.go.coverage.reportPaths=coverage.out

# Encoding
sonar.sourceEncoding=UTF-8